import fs from "node:fs";import assert from "node:assert/strict";
const html=fs.readFileSync(new URL("../public/index.html",import.meta.url),"utf8");
const js=fs.readFileSync(new URL("../public/js/app.js",import.meta.url),"utf8");
const pos=fs.readFileSync(new URL("../public/js/pos-enhance.js",import.meta.url),"utf8");
const css=fs.readFileSync(new URL("../public/pos-theme.css",import.meta.url),"utf8");
const api=fs.readFileSync(new URL("../functions/api/[[path]].js",import.meta.url),"utf8");
assert.match(html,/CANTIN POS/);
assert.equal((html.match(/class="nav/g)||[]).length,7);
for(const x of ["dashboard","sales","debts","warehouse","cashflow","reports","catalog","more"])assert.match(html,new RegExp(`data-page="${x}"`));
for(const x of ["reportRevenue","reportProfit","reportOrders","reportAverageOrder","reportTopProducts","reportPayments","reportStock","reportDebt"])assert.match(html,new RegExp(x));
for(const x of ["debtSort","debtStatus","debtFrom","debtTo","clearDebtFilters"])assert.match(html,new RegExp(x));
for(const x of ["exportStore","exportExcel","exportZip","importStore","addCashEntry","closeCashSession","showEditDebt","showEditDebtPayment"])assert.match(js,new RegExp(x));
assert.match(pos,/refreshReports/);assert.match(pos,/cantin-pos:last-page/);assert.match(pos,/e\.key==='F2'/);assert.match(css,/@media\(min-width:980px\)/);assert.match(css,/\.report-grid/);
for(const x of ["sale.create","debt.update","debt.payment.update","debt.payment.delete","stockin.create","cash.entry.create","supplier.create","supplier.pay","cash.session.close"])assert.match(api,new RegExp(`case "${x.replaceAll('.', '\\.')}`));
assert.match(api,/rebuildDebtCashEntries/);assert.match(api,/cashEntries/);assert.match(api,/supplierDebts/);assert.match(js,/Giá nhập\/thùng/);assert.match(js,/stockinLineCalc/);assert.match(api,/caseCost/);assert.match(api,/cases\*caseCost\+units\*unitCost/);
console.log("PASS Cantin POS static - POS shell, reports, persistence, inventory and debt workflows");
